/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.orchid.view;

import com.orchid.controller.ProductController;
import com.orchid.model.Product;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nabin
 */
public class AddProduct extends javax.swing.JInternalFrame {
   DefaultTableModel model;
    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
        model=new DefaultTableModel(null,new String[]{"Id","Name","Price","Qty","Remarks"});
        jTable_Product.setModel(model);
    }
    
    private void clearTable(){
        int count=jTable_Product.getRowCount();
        for(int i=0;i<count;i++){
            model.removeRow(0);
        }
    }
    
    private void clearFields(){
        jLabel_Id.setText("Id");
        jTextField_Name.setText("");
        jTextField_Price.setText("");
        jTextField_Qty.setText("");
        jTextArea_Remarks.setText("");
    }
    
    private void loadData(){
          clearTable();
        ProductController pdc=new ProductController();
        ArrayList<Product> list=pdc.fetchData();
        for(int i=0;i<list.size();i++){
            model.addRow(new Object[]{list.get(i).getId(),
            list.get(i).getNames(),list.get(i).getPrice(),
            list.get(i).getQty(),list.get(i).getRemarks()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Price = new javax.swing.JTextField();
        jTextField_Qty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Remarks = new javax.swing.JTextArea();
        jButton_Save = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Product = new javax.swing.JTable();
        jButton_LoadData = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jLabel_Id = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Add Product");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Price");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Qty");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Remarks");

        jTextField_Name.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        jTextField_Price.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jTextField_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_PriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PriceKeyTyped(evt);
            }
        });

        jTextField_Qty.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jTextField_Qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_QtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_QtyKeyTyped(evt);
            }
        });

        jTextArea_Remarks.setColumns(20);
        jTextArea_Remarks.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jTextArea_Remarks.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Remarks);

        jButton_Save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jTable_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Product);

        jButton_LoadData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_LoadData.setText("Load Data");
        jButton_LoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoadDataActionPerformed(evt);
            }
        });

        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jLabel_Id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Id.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Delete))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_Qty)
                                .addComponent(jTextField_Price)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_Name))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Id)
                        .addGap(88, 88, 88)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jButton_LoadData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel_Id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Save)
                            .addComponent(jButton_Update)
                            .addComponent(jButton_Delete)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton_LoadData)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        String name=jTextField_Name.getText();
        double price=Double.parseDouble(jTextField_Price.getText());
        int qty=Integer.parseInt(jTextField_Qty.getText());
        String remarks=jTextArea_Remarks.getText();
        
        //create object of model class Product and set these values
        Product ob=new Product();
        ob.setNames(name);
        ob.setPrice(price);
        ob.setQty(qty);
        ob.setRemarks(remarks);
        
        //Pass this object to ProductController class 
        ProductController pdc=new ProductController();
        pdc.saveProduct(ob);
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_LoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoadDataActionPerformed
        // TODO add your handling code here:
      loadData();
        
    }//GEN-LAST:event_jButton_LoadDataActionPerformed

    private void jTable_ProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ProductMouseClicked
        // TODO add your handling code here:
        int row=jTable_Product.getSelectedRow();
     jLabel_Id.setText(jTable_Product.getValueAt(row, 0).toString());
     jTextField_Name.setText(jTable_Product.getValueAt(row, 1).toString());
     jTextField_Price.setText(jTable_Product.getValueAt(row, 2).toString());
     jTextField_Qty.setText(jTable_Product.getValueAt(row, 3).toString());
     jTextArea_Remarks.setText(jTable_Product.getValueAt(row,4).toString());
             
        
    }//GEN-LAST:event_jTable_ProductMouseClicked

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(jLabel_Id.getText());
        ProductController pdc=new ProductController();
        pdc.deleteProduct(id);
        loadData();
        clearFields();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        Product ob=new Product();
        ob.setId(Integer.parseInt(jLabel_Id.getText()));
        ob.setNames(jTextField_Name.getText());
        ob.setPrice(Double.parseDouble(jTextField_Price.getText()));
        ob.setQty(Integer.parseInt(jTextField_Qty.getText()));
        ob.setRemarks(jTextArea_Remarks.getText());
        
        ProductController pdc=new ProductController();
        pdc.updateProduct(ob);
        loadData();
        clearFields();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jTextField_PriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PriceKeyReleased
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTextField_PriceKeyReleased

    private void jTextField_QtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_QtyKeyReleased
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTextField_QtyKeyReleased

    private void jTextField_PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PriceKeyTyped
        // TODO add your handling code here:
         char ch=evt.getKeyChar();
        if(!(ch>='0' && ch<='9')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_PriceKeyTyped

    private void jTextField_QtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_QtyKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if(!(ch>='0' && ch<='9')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_QtyKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_LoadData;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Product;
    private javax.swing.JTextArea jTextArea_Remarks;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Price;
    private javax.swing.JTextField jTextField_Qty;
    // End of variables declaration//GEN-END:variables
}
